version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    platform: linux/amd64
    tty: true